server:
  port: 9191
  servlet:
    context-path: /auth/admin
spring:
  liquibase:
    change-log: classpath:master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
logging:
  level:
    org:
      hibernate:
        type: trace
      springframework:
        security: DEBUG
  file: demo.log
application:
  healthchek:
    url: ${HEALTH_CHECK_URL:http://localhost:9191/auth/admin/login}
management:
  endpoint:
    shutdown:
      enabled: true
    logfile:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"