server:
  port: 9292
  servlet:
    context-path: /auth/admin
spring:
  liquibase:
    change-log: classpath:master.xml
    enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    driver-class-name: org.h2.Driver
    continue-on-error: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration